Testing `suite-with-failures'.
This run has ID `<uuid>'.

  ...           test-a          0   Passing.  [OK]          test-a          0   Passing.
  ...           test-a          1   Failing.> [FAIL]        test-a          1   Failing.
  ...           test-b          0   Another pass.  [OK]          test-b          0   Another pass.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        test-a          1   Failing.                                   │
└──────────────────────────────────────────────────────────────────────────────┘
[exception] Dune__exe__Exception_in_test.Foo("message")

Logs saved to `<build-context>/_build/_tests/suite-with-failures/test-a.001.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `<build-context>/_build/_tests/suite-with-failures'.
1 error! in <test-duration>s. 3 tests run.
